[package]
name = "samples_client"
version = "0.0.1"
edition.workspace = true
publish = false

[dependencies]
mssf-core.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true